---
title: "Risk Analysis and Risk Reporting of a bank"
author: "Vigan Hamzai"
date: "December 23, 2022"
output:
  pdf_document:
    keep_tex: true
    toc: yes
    toc_depth: '3'
  html_document:
    toc: yes
    toc_depth: 3
    code_folding: hide
    fig_caption: yes
fontsize: 12pt
---

```{r, echo = F, warning = F, include = F}
library(dplyr)
library(ggplot2)
library(bsts)
library(knitr)
library(kableExtra)
library(magrittr)
library(flextable)
```

\newpage

# Abstract

\newpage

# 1. Introduction

## Goals and Tasks

\newpage

# 2. Theoretical foundations

## Financial Statements

### Balance Sheet

### Income Statement

## Financial Analysis

### Liquidity

### Value and income

## Risk Analysis

### Sensitivity

## Financial Elements

### Financial Contracts

### Behavioral elements

### Risk Factors

### Counterparties

## Financial Events

\newpage

# 3. Approaches and Methods

## Replicating a bank's financial contracts

### Institution

The institution object serves as a top level container which represents the bank's hierarchy of the financial statements parts such as assets, liabilities and operations (revenues and expenses) and their underlying child objects and leaves.

| Assets       | Liabilities |
|--------------|-------------|
| Short Term   | Short Term  |
| Long Term    | Long Term   |
| Fixed Assets | Equity      |

: Balance Sheet

| Col1 | Col2 |
|------|------|
|      |      |
|      |      |
|      |      |

: Income Statement

\newpage

# 4. Results

\newpage

# 5. Discussion and Outlook

\newpage

# 6. References

\newpage

# 7. Appendix
