##############################################################
#' \code{presentValue}
#'
#' Function that calculates the Net Present Value (NPV) for the cash flow streams 
#' generated by or contained in object \code{x}.
#' 
#' @param x a contract type, for which to calculate the NPV. This can also be 
#'          a timeSeries, EventSeries or Portfolio object.
#' 
#' @param yield a numeric, an object of type \code{\link{YieldCurve}} or 
#'                    \code{\link{DynamicYieldcurve}} to calculate discount 
#'                    factors from, indicating the percentage yield used to discount.
#'
#' @param by a character indicating the date as for which the NPV is calculated.
#'  
#' @param isPercentage a logical, indicating if the 'yield' is passed as percentage 
#'                     (TRUE) or as fraction (FALSE) (default is TRUE). 
#'                     
#' @param isPrice a logical indicating whether the result should be a price
#'                in the case of a cash flow pattern where the initial cash flow
#'                is negative and the others are positive (default is FALSE).   
#'                
#' @param digits an integer indicating the number of digits to round to. (default is 2)          
#' 
#' @return a numeric, representing the Net Present Value (NPV) of the contract. 
#' 
#' @usage presentValue(x, yield, by, isPercentage, isPrice, digits)
#' 
#' @examples
#' b <- bond("2013-12-31", maturity = "5 years", nominal = 50000, 
#'            coupon = 0.02, couponFreq = "1 years")
#' npv <- presentValue(b, yield = 2) # result: 0 due to same coupon as yield
#' evs <- events(b, "2013-12-31")
#' npv <- presentValue(evs, yield = 1)
#' ts <- timeSeries(data = c(-50000, 1000, 1000, 1000, 1000, 51000),
#'                  charvec = c("2013-12-31", "2014-12-31", "2015-12-31", 
#'                  "2016-12-31", "2017-12-31", "2018-12-31"),
#'                  units = "Value")
#' npv <- presentValue(ts, yield = 1)
#' 
#' @include DynamicYieldCurve.R 
#' @include YieldCurve.R
#' @export
#' 
setGeneric(name = "presentValue", def = function(object, yield, ...){
  standardGeneric("presentValue")
})


#' @include DynamicYieldCurve.R 
#' @include YieldCurve.R
#' @export
#' 
setMethod(f = "presentValue", signature = c("EventSeries", "YieldCurve"),
          definition = function(object, yield, by=NULL, isPercentage=TRUE, isPrice=FALSE, digits=2, 
                                method="compound", period="Y", convention="30E360", ...){
 
            events_df <- object$events_df
            
            yearFractions <- c(0)
            for(i in 2:nrow(events_df)){
              fraction <- yearFraction(as.character(events_df[1,"time"]), as.character(events_df[i,"time"]), convention = "30E360")
              yearFractions <- c(yearFractions, fraction)
            }
            
            events_df$fraction <- yearFractions
            
            evs <- events_df[,c("time","payoff","type", "fraction")]
            
            if(is.null(by)) {
              by <- as.character(evs$time[1])
            }
            
            if (evs[evs$time==by,"type"]=="IED") {
              evs <- evs[evs$time>by,]
            } else {
              evs <- evs[evs$time>=by,]
            }
            
            evs <- evs[!(evs$type %in% c("IPCI","DPR","PRF","RR","RRY","SC","PRY")),]
            evs <- evs[!((evs$type %in% "AD0") & (evs$payoff==0)),]
            
            
            if (dim(evs)[1]==0) {
              cf <- timeSeries(cbind(0,0), 
                               charvec = by, 
                               units = c("payoff","fraction"))
            }else{
              if (evs$type[dim(evs)[1]]!="MD" & evs$payoff[dim(evs)[1]]==0){
                evs <- evs[1:dim(evs)[1]-1,]
              }
              
              evs.ts <- timeSeries(evs[,c("payoff","fraction")], charvec=substring(evs$time,1,10))
              evs.ts$fraction <- as.numeric(evs.ts$fraction)
              evs.ts$payoff <- as.numeric(evs.ts$payoff)
              cf <- aggregate(evs.ts, time(evs.ts), "sum")
              cf$fraction <- evs.ts[row.names(cf),]$fraction
            }
            
            df <- discountFactors(yield, to=as.character(time(cf)), method = method, period = period)
            
            # compute and return present value
            out <- c()
            for (i in 1:(ncol(cf)-1)) {
              cf_temp <- cf[,c(i,ncol(cf))]
              out <- c(out, as.numeric(t(cf_temp$payoff)%*%df))
            }
            
            return (round(out,digits))
})
